name: NaturalParkour
version: "@VERSION@"
author: NaturalDev
description: Randomly generated parkour!
website: https://github.com/Natural-Minecraft/NaturalParkour
main: id.naturalsmp.naturalparkour.Main
softdepend: [PlaceholderAPI, WorldEdit]
api-version: 1.13

commands:
  naturalparkour:
    description: NaturalParkour commands
    aliases: [nparkour, npk, parkour]
    usage: "/naturalparkour, /parkour"
