name: NaturalParkour
version: "@VERSION@"
author: NaturalSMP
description: Randomly generated parkour!
website: https://github.com/Natural-Minecraft/NaturalParkour
main: us.ajg0702.parkour.Main
softdepend: [PlaceholderAPI, WorldEdit]
api-version: 1.13

commands:
  naturalparkour:
    description: NaturalParkour commands
    aliases: [nparkour, npk, parkour, ap, ajp, ajpk, apk]
    usage: "/naturalparkour, /parkour"
